// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Snap.Hutao.Server.Model.Context;

#nullable disable

namespace Snap.Hutao.Server.Model.Migrations
{
    [DbContext(typeof(MetadataDbContext))]
    partial class MetadataDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.GachaEventInfo", b =>
                {
                    b.Property<string>("Version")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Locale")
                        .HasColumnType("varchar(255)");

                    b.Property<uint>("Order")
                        .HasColumnType("int unsigned");

                    b.Property<DateTime>("From")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("To")
                        .HasColumnType("datetime");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<uint>("UpOrangeItem1")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem10")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem11")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem12")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem13")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem14")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem15")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem16")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem17")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem2")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem3")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem4")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem5")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem6")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem7")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem8")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpOrangeItem9")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpPurpleItem1")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpPurpleItem2")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpPurpleItem3")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpPurpleItem4")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UpPurpleItem5")
                        .HasColumnType("int unsigned");

                    b.HasKey("Version", "Name", "Locale", "Order");

                    b.ToTable("gacha_events");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.KnownItem", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int unsigned");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<uint>("Id"));

                    b.Property<uint>("Quality")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id");

                    b.ToTable("known_items");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataAchievement", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FinishReward")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<uint>("Goal")
                        .HasColumnType("int unsigned");

                    b.Property<bool>("IsDailyQuest")
                        .HasColumnType("tinyint(1)");

                    b.Property<uint>("Order")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("PreviousId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Progress")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Title")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("varchar(32)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_achievements");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataAchievementGoal", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("FinishReward")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("Order")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_achievement_goals");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataAvatar", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("BaseValue")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<uint>("Body")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Costumes")
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("FetterInfo")
                        .HasColumnType("json");

                    b.Property<string>("GrowCurves")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("Quality")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SideIcon")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("SkillDepot")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<uint>("Sort")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Weapon")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_avatars");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataBeyondItem", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_beyond_items");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataChapter", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<uint>("CityId")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("GroupId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("ImageTitle")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Number")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Title")
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_chapters");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataDisplayItem", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<uint>("ItemType")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<string>("TypeDescription")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_display_items");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataFurniture", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<uint>("Comfort")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("Cost")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<string>("SourceTexts")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_furniture");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataFurnitureMake", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<uint>("Experience")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("ItemId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Materials")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_furniture_makes");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataFurnitureSuite", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Types")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Units")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_furniture_suites");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataFurnitureType", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<uint>("Category")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Name2")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("Sort")
                        .HasColumnType("int unsigned");

                    b.Property<string>("TabIcon")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_furniture_types");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataHyperLinkName", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_hyper_link_names");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataMaterial", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint>("ItemType")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("MaterialType")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<string>("TypeDescription")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_materials");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataMonster", b =>
                {
                    b.Property<uint>("DescribeId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<uint>("Arkhe")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Title")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("Type")
                        .HasColumnType("int unsigned");

                    b.HasKey("DescribeId", "Locale");

                    b.ToTable("metadata_monsters");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataNameCard", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("Pictures")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_name_cards");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataProfilePicture", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("UnlockParameter")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("UnlockType")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_profile_pictures");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataReliquary", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<uint>("EquipType")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Ids")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("SetId")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_reliquaries");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataReliquarySet", b =>
                {
                    b.Property<uint>("SetId")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("EquipAffixIds")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<string>("NeedNumber")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("SetId", "Locale");

                    b.ToTable("metadata_reliquary_sets");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataRoleCombatSchedule", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<DateTime>("Begin")
                        .HasColumnType("datetime");

                    b.Property<string>("Elements")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<DateTime>("End")
                        .HasColumnType("datetime");

                    b.Property<string>("InitialAvatars")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("SpecialAvatars")
                        .IsRequired()
                        .HasColumnType("json");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_role_combat_schedules");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataTowerSchedule", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("BuffName")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime>("Close")
                        .HasColumnType("datetime");

                    b.Property<string>("Descriptions")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("FloorIds")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<DateTime>("Open")
                        .HasColumnType("datetime");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_tower_schedules");
                });

            modelBuilder.Entity("Snap.Hutao.Server.Model.Metadata.MetadataWeapon", b =>
                {
                    b.Property<uint>("Id")
                        .HasColumnType("int unsigned");

                    b.Property<string>("Locale")
                        .HasMaxLength(16)
                        .HasColumnType("varchar(16)");

                    b.Property<string>("Affix")
                        .HasColumnType("json");

                    b.Property<string>("AwakenIcon")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("CultivationItems")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<string>("GrowCurves")
                        .IsRequired()
                        .HasColumnType("json");

                    b.Property<string>("Icon")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<uint>("RankLevel")
                        .HasColumnType("int unsigned");

                    b.Property<uint>("WeaponType")
                        .HasColumnType("int unsigned");

                    b.HasKey("Id", "Locale");

                    b.ToTable("metadata_weapons");
                });
#pragma warning restore 612, 618
        }
    }
}
