version: '3.8'

services:
  homa-server:
    build:
      context: .
      dockerfile: Snap.Hutao.Server/Dockerfile
      target: final
    image: homa-server:latest
    ports:
      - "5076:80"
    extra_hosts:
      - "host.docker.internal:172.27.0.1"
      - "host.docker.gateway:host-gateway"
    container_name: Homa-Server
    volumes:
      - ./appsettings-homa.json:/app/appsettings.json
    restart: unless-stopped
    depends_on:
      - redis

  api-server:
    build:
      context: .
      dockerfile: Snap.Hutao.Server.API/Dockerfile
      target: final
    image: api-server:latest
    ports:
      - "5077:80"
    extra_hosts:
      - "host.docker.internal:172.27.0.1"
      - "host.docker.gateway:host-gateway"
    container_name: API-Server
    volumes:
      - ./appsettings-api.json:/app/appsettings.json
    restart: unless-stopped
    depends_on:
      - redis
      - homa-server

  redis:
    container_name: Hutao-Server-Redis
    image: redis:latest
    volumes:
      - ./redis:/data
    restart: unless-stopped
